### ISSUE TITLE
Stack smashing detected

### ISSUE THREAD

**Issue by squidink7** [jcweaver997/vgdextension#6]
When building the example with either `-cc clang` or `-prod` (or both) launching the project in Godot crashes with `*** stack smashing detected ***: terminated`

V version: master
Godot version: 4.3 dev 3

**Comment by jcweaver997** [comment]
I was able to reproduce and was able to resolve it in https://github.com/jcweaver997/vgdextension/commit/2a88b222d9a8b5caff95ff3bec0517b1e25f3849

Please re-open or create a new issue if you find any issues
